### ISSUE TITLE
Great start - next up sensors in Home Assistant.

### ISSUE THREAD

**Issue by kineticscreen** [orbforge/addon-orb#1]
This is extremely cool. I'm wonder how hard it would be to get some of the data into Home Assistant proper as devices / sensors? I'm seeing in the logs that MQTT is somehow being leveraged, is that how the data packets are being communicated between Orbs? Is there a way of getting them seen by the MQTT broker?

**Comment by BenAChilds** [comment]
+1 for sensors. Seems like little point having all of this monitoring but no way to leverage the information.

**Comment by mhalano** [comment]
Yeah. Very relevant. I was using the Speed Test integration, but I think Orb can replace it easily.

**Comment by csfolmer** [comment]
Yes same request here

**Comment by kineticscreen** [comment]
Hopefully everyone here has realised that this is now available, by switching on a toggle in the Add On settings.

Now we need to get some good gauge dashboards! What would be really good is to match the gradatcolouring segments for the % values.

**Comment by mhalano** [comment]
I saw it pushes to MQTT, which is good, but I was hoping for a proper service which I can put in my main dashboard. Today I still have to use the older SpeedTest one to get the speed of my Internet link.

**Comment by mhalano** [comment]
But yeah, maybe someone uses an external MQTT service, so it would be nice to configure.

**Comment by DIMMonchik** [comment]
> But yeah, maybe someone uses an external MQTT service, so it would be nice to configure.

I have just such a case - MQTT on another server

**Comment by kineticscreen** [comment]
OK so using the [Modern Circular Gauge](https://github.com/selvalt7/modern-circular-gauge) card I've created this:

<img width="524" alt="Image" src="https://github.com/user-attachments/assets/e228740a-ef2d-467a-be33-9d3d271594ef" />

```
type: custom:modern-circular-gauge
entity: sensor.orb_sensor_score
secondary:
  adaptive_state_color: true
  show_gauge: none
tertiary: {}
header_position: bottom
needle: false
grid_options:
  columns: 6
  rows: 3
name: Orb Score
icon: mdi:lightning-bolt
segments:
  - from: 0
    color:
      - 240
      - 58
      - 72
  - color:
      - 249
      - 158
      - 73
    from: 50
  - from: 70
    color:
      - 185
      - 195
      - 76
  - from: 80
    color:
      - 121
      - 184
      - 82
  - from: 90
    color:
      - 24
      - 176
      - 90
adaptive_icon_color: false
adaptive_state_color: true
show_icon: true
show_unit: true
show_state: true
smooth_segments: false
```

And also with its custom Badges:

<img width="335" alt="Image" src="https://github.com/user-attachments/assets/76c5a861-a775-4e0f-b77f-e8d282f448a2" />

```
type: custom:modern-circular-gauge-badge
entity: sensor.orb_sensor_score
name: Orb Score
show_name: true
show_icon: true
icon: mdi:lightning-bolt
segments:
  - from: 0
    color:
      - 240
      - 58
      - 72
  - color:
      - 249
      - 158
      - 73
    from: 50
  - from: 70
    color:
      - 185
      - 195
      - 76
  - from: 80
    color:
      - 121
      - 184
      - 82
  - from: 90
    color:
      - 24
      - 176
      - 90
```
