### ISSUE TITLE
Packet Loss MQTT definition - unit_of_measurement missing

### ISSUE THREAD

**Issue by adamind** [orbforge/addon-orb#7]
Hi team
Thanks for making this available
I've noticed that the "Packet Loss" MQTT Sensor is not getting updated in Home Assistant
I can see the current Orb Sensor Packet Loss (sensor.orb_sensor_packet_loss) defined in Home Assistant as follows:

```

MQTT discovery data:
Topic: homeassistant/sensor/orb_packet_loss/config
Payload
state_topic: orb_homeassistant/status
unit_of_measurement: ''
value_template: >-
  {{
  value_json.orb_score.components.reliability_score.components.internet_loss_status.value
  | round(0) }}
unique_id: packet_loss
device:
  identifiers:
    - orb
  manufacturer: Orb Forge
  model: Orb Agent
  name: Orb Sensor
name: Packet Loss
```

Note the value_template is split over two lines, which I believe is an issue and may be causing this issue. unit_of_measurement is also missing

I see mqtt.sh is generating the above, and the Packet Loss line in the mapping section is missing a % at the end
